use regex::Regex;
use std::sync::LazyLock;

pub struct Rule {
    pub id: &'static str,
    pub provider: &'static str,
    pub secret_type: &'static str,
    pub risk_level: &'static str,
    pub description: &'static str,
    pub regex: Regex,
}

pub static RULES: LazyLock<Vec<Rule>> = LazyLock::new(|| vec![
    Rule {
        id: "aws-access-key",
        provider: "aws",
        secret_type: "api_key",
        risk_level: "critical",
        description: "AWS Access Key ID",
        regex: Regex::new(r"AKIA[A-Z0-9]{16}").unwrap(),
    },
    Rule {
        id: "aws-secret-key",
        provider: "aws",
        secret_type: "api_key",
        risk_level: "critical",
        description: "AWS Secret Access Key",
        regex: Regex::new(r"(?i)aws_secret_access_key\s*[:=]\s*[A-Za-z0-9/+=]{40}").unwrap(),
    },
    Rule {
        id: "github-pat",
        provider: "github",
        secret_type: "token",
        risk_level: "critical",
        description: "GitHub Personal Access Token",
        regex: Regex::new(r"ghp_[A-Za-z0-9]{36,}").unwrap(),
    },
    Rule {
        id: "github-oauth",
        provider: "github",
        secret_type: "token",
        risk_level: "critical",
        description: "GitHub OAuth Token",
        regex: Regex::new(r"gho_[A-Za-z0-9]{36,}").unwrap(),
    },
    Rule {
        id: "github-app",
        provider: "github",
        secret_type: "token",
        risk_level: "high",
        description: "GitHub App Token",
        regex: Regex::new(r"ghs_[A-Za-z0-9]{36,}").unwrap(),
    },
    Rule {
        id: "stripe-secret",
        provider: "stripe",
        secret_type: "api_key",
        risk_level: "critical",
        description: "Stripe Secret Key",
        regex: Regex::new(r"sk_live_[A-Za-z0-9]{20,}").unwrap(),
    },
    Rule {
        id: "stripe-publishable",
        provider: "stripe",
        secret_type: "api_key",
        risk_level: "medium",
        description: "Stripe Publishable Key",
        regex: Regex::new(r"pk_live_[A-Za-z0-9]{20,}").unwrap(),
    },
    Rule {
        id: "private-key",
        provider: "generic",
        secret_type: "ssh_key",
        risk_level: "critical",
        description: "Private Key",
        regex: Regex::new(r"-----BEGIN\s+(RSA|DSA|EC|OPENSSH|PGP)\s+PRIVATE\s+KEY-----").unwrap(),
    },
    Rule {
        id: "gcp-api-key",
        provider: "gcp",
        secret_type: "api_key",
        risk_level: "high",
        description: "Google Cloud API Key",
        regex: Regex::new(r"AIza[A-Za-z0-9_-]{35}").unwrap(),
    },
    Rule {
        id: "slack-token",
        provider: "slack",
        secret_type: "token",
        risk_level: "high",
        description: "Slack Token",
        regex: Regex::new(r"xox[bporas]-[A-Za-z0-9-]{10,}").unwrap(),
    },
    Rule {
        id: "jwt",
        provider: "generic",
        secret_type: "token",
        risk_level: "high",
        description: "JSON Web Token",
        regex: Regex::new(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}").unwrap(),
    },
]);
